# Generated by Django 3.0.3 on 2020-10-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='profile',
            field=models.ManyToManyField(to='catalog.Profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Profile'),
        ),
    ]
