# Generated by Django 3.1.2 on 2020-10-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201012_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='profile',
            new_name='past_profiles',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='current_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookinstance_current_books', to='catalog.profile'),
        ),
    ]
