# Generated by Django 3.1.2 on 2020-10-17 09:36

from django.db import models, migrations
from django.contrib.auth.models import Group, Permission
import logging

logger = logging.getLogger(__name__)

def add_group_permissions(apps, schema_editor):
    #Admin
    group, created = Group.objects.get_or_create(name='Admin')   
    if created:
        logger.info('Admin Group created')

    #Users
    group, created = Group.objects.get_or_create(name='Users') 
    if created:
        logger.info('Users Group created')


    #Managers
    group, created = Group.objects.get_or_create(name='Managers') 
    if created:
        logger.info('Managers Group created')

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201015_1044'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
