# Generated by Django 3.1.2 on 2020-12-22 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201222_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.BigIntegerField(blank=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)]),
        ),
    ]
