# Generated by Django 3.1.2 on 2020-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201222_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.TextField(blank=True, max_length=8),
        ),
    ]
